### ISSUE TITLE
Checkout apps and dependencies in add command

### ISSUE THREAD

**Issue by MeiyappanKannappa** [MeiyappanKannappa/shalo#8]
**Current State**
It supports only to add folders in the shalo add command
```
shalo add <folder_name>
```
What if the user want to add another NX project.
 **Proposed Changes**
- add a flag --folder-only or -f, if so with this flag only the folder will be added to checkout. If not the change should compute graph from existing output.json, and checkout additional dependencies for the app.
- Updated readme.md file with the instructions

**Comment by Sagar2006** [comment]
kindly assign me this issue. I will try my best to tackle this issue.!!!!

**Comment by Sagar2006** [comment]
please check i created a pull request for this issue
